- hosts: all
  gather_facts: yes
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"

  tasks:
    - name: Run versionReport V1.0.ps1
      win_shell: |
        $p = "C:\ARFILES\VersionReport\versionReport V1.0.ps1"
        if (Test-Path $p) {
          Write-Output "Running script"
          & $p
          Write-Output "Script executed successfully"
        } else {
          Write-Output "Script not found"
        }
      register: run_script_result
      ignore_errors: yes
      changed_when: "'Script executed successfully' in run_script_result.stdout"

    - name: Show script output in AWX
      debug:
        var: run_script_result.stdout
