- hosts: all
  gather_facts: yes
  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"

  tasks:
    - name: Get last modified date of DymocksLoyalty folder
      win_shell: |
        $folder = "C:\ApplicationUpdates\Plugins\DymocksLoyalty"
        $hostname = $env:COMPUTERNAME
        if (Test-Path $folder) {
          $lastModified = (Get-Item $folder).LastWriteTime
          $formattedDate = $lastModified.ToString("yyyy-MM-dd")
          $today = (Get-Date).ToString("yyyy-MM-dd")
          $ipAddress = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.IPAddress -match "^\d+\.\d+\.\d+\.\d+$"} | Select-Object -First 1).IPAddress
          if ($formattedDate -ge $today) {
            Write-Output "Last Modified Date: $formattedDate - ✅ DymocksLoyalty Plugins Successfully Copied in $hostname IP: $ipAddress"
          } else {
            Write-Output "Last Modified Date: $formattedDate - ❌ DymocksLoyalty Plugins Copy Failed in $hostname IP: $ipAddress"
          }
        } else {
          Write-Output " ❌ DymocksLoyalty Folder not found in ARFiles location in $hostname. Please copy the file"
        }
      register: dymocksLoyalty_modified_date
      ignore_errors: yes
      changed_when: false

    - name: Show folder modification status
      ansible.builtin.debug:
        var: dymocksLoyalty_modified_date.stdout
      when: dymocksLoyalty_modified_date.stdout is defined
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
