---
- hosts: all
  gather_facts: yes
  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"
  tasks:
    - name: Get last modified date of DymocksBooklover folder
      win_shell: |
        $folder = "C:\Program Files (x86)\AdvanceRetail\EXE\Plugins\DymocksBooklover"
        if (Test-Path $folder) {
          $lastModified = (Get-Item $folder).LastWriteTime
          $formattedDate = $lastModified.ToString("yyyy-MM-dd HH:mm:ss")
          $today = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
          if ($lastModified -lt (Get-Date)) {
            Write-Output "Last Modified Date: $formattedDate - ✅ Successfully Copied"
          } else {
            Write-Output "Last Modified Date: $formattedDate - ❌ Copy Failed"
          }
        } else {
          Write-Output "Folder not found!"
        }
      register: booklover_modified_date
      changed_when: false

    - name: Display last modified date and status with IP
      ansible.builtin.debug:
        msg: "{{ booklover_modified_date.stdout | default('Folder not found!') }}"
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
