- hosts: all
  gather_facts: yes
  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"

  tasks:
    - name: Get last modified date of DymocksLoyalty folder
      win_shell: |
        $folder = "C:\ARFiles\DymocksLoyaltyUpgrade"
        $hostname = $env:COMPUTERNAME
        $ipAddress = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.InterfaceAlias -notmatch "Loopback"} | Select-Object -First 1).IPAddress
        if (Test-Path $folder) {
          $lastModified = (Get-Item $folder).LastWriteTime
          $thresholdDate = (Get-Date).AddDays(-60)
          if ($lastModified -ge $thresholdDate) {
            Write-Output "✅ SUCCESS: DymocksLoyaltyUpgrade Plugins Copied - Last Modified: $($lastModified.ToString('yyyy-MM-dd')) on $hostname (IP: $ipAddress)"
          } else {
            Write-Output "❌ ERROR: DymocksLoyaltyUpgrade Plugins Copy Failed - Last Modified: $($lastModified.ToString('yyyy-MM-dd')) on $hostname (IP: $ipAddress)"
          }
        } else {
          Write-Output "❌ ERROR: DymocksLoyaltyUpgrade Folder Not Found in ARFiles on $hostname (IP: $ipAddress). Please copy the file."
        }
      register: dymocksLoyalty_modified_date
      ignore_errors: yes
      changed_when: false

    - name: Show folder modification status
      ansible.builtin.debug:
        var: dymocksLoyalty_modified_date.stdout
      when: dymocksLoyalty_modified_date.stdout is defined

  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
