- hosts: all
  gather_facts: yes
  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"

  tasks:
    - name: Get last modified date of DymocksBooklover folder
      win_shell: |
        $folder = "C:\Program Files (x86)\AdvanceRetail\EXE\Plugins\DymocksBooklover"
        if (Test-Path $folder) {
          $lastModified = (Get-Item $folder).LastWriteTime
          $formattedDate = $lastModified.ToString("yyyy-MM-dd HH:mm:ss")
          $today = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
          $ipAddress = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.IPAddress -match "^\d+\.\d+\.\d+\.\d+$"} | Select-Object -First 1).IPAddress
          if ($lastModified -lt (Get-Date)) {
            Write-Output "Last Modified Date: $formattedDate - ✅ Successfully Copied New BookLover from IP: $ipAddress"
          } else {
            Write-Output "Last Modified Date: $formattedDate - ❌ Copy Failed from IP: $ipAddress"
          }
        } else {
          Write-Output "Folder not found!"
        }
      register: booklover_modified_date
      changed_when: false

    - name: Show folder modification status
      ansible.builtin.debug:
        var: booklover_modified_date.msg
