---
- hosts: all
  gather_facts: yes
  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"

  tasks:
    - name: Rename existing DymocksLoyalty folder if it exists
      win_shell: |
        if (Test-Path "C:\Program Files (x86)\AdvanceRetail\EXE\Plugins\DymocksLoyalty_V2.8009.0.10") {
          Rename-Item -Path "C:\Program Files (x86)\AdvanceRetail\EXE\Plugins\DymocksLoyalty_V2.8009.0.10" -NewName "C:\Program Files (x86)\AdvanceRetail\EXE\Plugins\DymocksLoyalty" -Force
        }
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only

