---
- hosts: all
  gather_facts: yes

  vars_prompt:
    - name: "survey_ip"
      prompt: "Enter the third octet of the source server IP (10.61.x.200)"
      private: no

  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"
    # Dynamically build the UNC path using user input
    source_share: "\\10.61.{{ survey_ip }}.200\ARFiles\DymocksLoyaltyUpgrade\Plugins\DymocksLoyalty"

  tasks:
    - name: Check if POS process is running
      win_command: powershell.exe -ExecutionPolicy Bypass -Command "Get-Process -Name 'POS' -ErrorAction SilentlyContinue"
      register: pos_process
      ignore_errors: yes

    - name: Stop POS process if running
      win_command: powershell.exe -ExecutionPolicy Bypass -Command "Stop-Process -Name 'POS' -Confirm:$false -Force"
      when: pos_process.rc == 0

    - name: Rename existing DymocksLoyalty folder if it exists
      win_shell: |
        if (Test-Path "C:\Program Files (x86)\AdvanceRetail\EXE\Plugins\DymocksLoyalty") {
          Rename-Item -Path "C:\Program Files (x86)\AdvanceRetail\EXE\Plugins\DymocksLoyalty" -NewName "C:\Program Files (x86)\AdvanceRetail\EXE\Plugins\DymocksLoyalty_V2.8009.0.10" -Force
        }

    - name: Pause briefly to ensure rename completes
      ansible.builtin.pause:
        seconds: 2

    - name: Copy DymocksLoyalty folder from network share to local Plugins folder
      win_command: |
        robocopy "{{ source_share }}" "C:\Program Files (x86)\AdvanceRetail\EXE\Plugins\DymocksLoyalty" /E /NFL /NDL /NP /R:3 /W:5
      register: robocopy_result
      ignore_errors: yes

    - name: Show robocopy output
      ansible.builtin.debug:
        var: robocopy_result.stdout_lines

  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
