- hosts: all
  gather_facts: yes
  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"
  tasks:
    - name: create upgrade folder
      win_command: >-
        powershell.exe -ExecutionPolicy Bypass -Command "if (Test-Path -Path 'C:\ARFiles\ApplicationUpdates\Plugins') {exit} else {New-Item -Path 'C:\ARFiles\ApplicationUpdates\Plugins' -ItemType Directory}"
    - name: Get last modified date of DymocksBooklover folder
      win_shell: |
        $folder = "C:\ARFiles\Application Updates\Plugins"
        $hostname = $env:COMPUTERNAME
        if (Test-Path $folder) {
          $lastModified = (Get-Item $folder).LastWriteTime
          $formattedDate = $lastModified.ToString("yyyy-MM-dd")
          $today = (Get-Date).ToString("yyyy-MM-dd")
          $ipAddress = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.IPAddress -match "^\d+\.\d+\.\d+\.\d+$"} | Select-Object -First 1).IPAddress
          if ($formattedDate -ge $today) {
            Write-Output "Last Modified Date: $formattedDate - ✅ C:\ARFiles\ApplicationUpdates\Plugins exist in $hostname IP: $ipAddress"
          } else {
            Write-Output "Last Modified Date: $formattedDate - ❌ C:\ARFiles\ApplicationUpdates\Plugins exist in $hostname IP: $ipAddress"
          }
        } else {
          Write-Output " ❌ C:\ARFiles\Application Updates\Plugins exist not found in ARFiles location in $hostname. Please create the file"
        }
      register: booklover_modified_date
      ignore_errors: 'yes'
      changed_when: false
  become: 'yes'
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
