---
- name: Run deleteS3content.bat and show log
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure tradeReportAppflowAutomation directory exists
      win_file:
        path: C:\trade_report_UA_backup\tradeReportAppflowAutomation
        state: directory
    - name: Run deleteS3content.bat
      win_shell: |
        & "C:\trade_report_UA_backup\tradeReportAppflowAutomation\venv\Scripts\python.exe" "C:\trade_report_UA_backup\tradeReportAppflowAutomation\deleteS3content.py"
      environment:
        AWS_ACCESS_KEY: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      register: bat_output
      ignore_errors: yes
    - name: Show deleteS3content.bat stdout
      debug:
        var: bat_output.stdout_lines

    - name: Show deleteS3content.bat stderr
      debug:
        var: bat_output.stderr_lines
