---
- name: Run deleteS3content.py with virtualenv and AWX credentials
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure script directory exists
      win_file:
        path: C:\trade_report_UA_backup\tradeReportAppflowAutomation
        state: directory
    - name: Run deleteS3content.py in virtual environment
      win_shell: C:\trade_report_UA_backup\venv\Scripts\python.exe C:\trade_report_UA_backup\tradeReportAppflowAutomation\deleteS3content_old.py
      register: delete_s3_output
      ignore_errors: yes
    - name: Show script stderr
      debug:
        var: delete_s3_output
