- name: Run deleteS3content.py on Windows hosts
  hosts: all
  gather_facts: yes

  vars:
    aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"
    script_path: "C:\\trade_report_UA_backup\\tradeReportAppflowAutomation\\deleteS3content.py"

  tasks:
    - name: Fail if AWS credentials are missing
      ansible.builtin.fail:
        msg: "AWS credentials are missing!"
      when: aws_access_key == "" or aws_secret_key == ""

    - name: Run deleteS3content.py
      ansible.windows.win_command:
        cmd: '"C:\Program Files\Python311\python.exe" "{{ script_path }}" "{{ aws_access_key }}" "{{ aws_secret_key }}"'
      register: script_result
      ignore_errors: yes

    - name: Show script status
      debug:
        msg: "Script finished with return code {{ script_result.rc | default('unknown') }}. Check the log on Windows host."
