---
- name: Run deleteS3content.py on Windows hosts
  hosts: windows
  gather_facts: no

  tasks:
    - name: Ensure log directory exists
      ansible.windows.win_file:
        path: C:\trade_report_UA_backup\tradeReportAppflowAutomation
        state: directory

    - name: Run deleteS3content.py with AWS credentials and log output
      ansible.windows.win_command: >
        cmd.exe /c
        python C:\trade_report_UA_backup\tradeReportAppflowAutomation\deleteS3content.py
        --aws-access-key={{ aws_access_key }}
        --aws-secret-key={{ aws_secret_key }}
        --bucket={{ bucket_name }}
        >> C:\trade_report_UA_backup\tradeReportAppflowAutomation\deleteS3content_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.log
        2>&1
      args:
        chdir: C:\trade_report_UA_backup\tradeReportAppflowAutomation
      register: script_result

    - name: Show script execution status
      debug:
        var: script_result.stdout


