- name: Run deleteS3content.py
  hosts: all
  gather_facts: no

  tasks:
    - name: Run deleteS3content.py
      win_command: python "C:\trade_report_UA_backup\tradeReportAppflowAutomation\deleteS3content.py"
      environment:
        AWS_ACCESS_KEY: "{{ aws_access_key }}"
        AWS_SECRET_KEY: "{{ aws_secret_key }}"
      register: py_output
      ignore_errors: yes

    - name: Show script stdout
      debug:
        var: py_output.stdout_lines
