---
- name: Run deleteS3content Python script via .bat
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure working directory exists
      win_file:
        path: C:\trade_report_UA_backup\tradeReportAppflowAutomation
        state: directory

    - name: Run deleteS3content .bat script
      win_command: cmd.exe /c "C:\trade_report_UA_backup\tradeReportAppflowAutomation\run_deleteS3.bat"
      register: delete_s3_output
      ignore_errors: yes

    - name: Show deleteS3content output
      debug:
        var: delete_s3_output.stdout_lines
