---
- name: Run deleteS3content.py on Windows hosts
  hosts: all
  gather_facts: yes

  vars:
    python_path: "C:\\Program Files\\Python311\\python.exe"
    script_dir: "C:\\trade_report_UA_backup\\tradeReportAppflowAutomation"
    script_name: "deleteS3content.py"

    # AWS credentials injected from AWX credential
    aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"

  tasks:

    - name: Fail if AWS credentials are missing
      ansible.builtin.fail:
        msg: "AWS credentials are missing!"
      when: aws_access_key == "" or aws_secret_key == ""

    - name: Ensure script directory exists
      ansible.windows.win_file:
        path: "{{ script_dir }}"
        state: directory

    - name: Run deleteS3content.py with AWS credentials
      ansible.windows.win_command:
        cmd: '"{{ python_path }}" "{{ script_name }}" {{ aws_access_key }} {{ aws_secret_key }}'
        chdir: "{{ script_dir }}"
      register: script_result
      ignore_errors: yes

    - name: Show script execution stdout
      ansible.builtin.debug:
        var: script_result.stdout_lines

    - name: Show script execution stderr
      ansible.builtin.debug:
        var: script_result.stderr_lines

    - name: Show script return code
      ansible.builtin.debug:
        msg: "Return code: {{ script_result.rc | default('unknown') }}"
