---
- name: Run deleteS3content.py on Windows hosts
  hosts: all
  gather_facts: no

  vars:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"

  tasks:
    - name: Ensure script directory exists
      ansible.windows.win_file:
        path: C:\trade_report_UA_backup\tradeReportAppflowAutomation
        state: directory

    - name: Run deleteS3content.py with AWS credentials
      ansible.windows.win_command: >
        "C:\Program Files\Python311\python.exe"
        "C:\trade_report_UA_backup\tradeReportAppflowAutomation\deleteS3content.py"
        "{{ aws_access_key }}" "{{ aws_secret_key }}"
      args:
        chdir: C:\trade_report_UA_backup\tradeReportAppflowAutomation
      register: script_result
      ignore_errors: yes

    - name: Show script execut



