- hosts: all
  gather_facts: yes
  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"
  tasks:
    - name: Run configureDymocksLoyalty.ps1
      win_shell: |
        $scriptPath = "C:\ARFILES\UpgradeMay2024\configureDymocksLoyalty.ps1"
        if (Test-Path $scriptPath) {
          Write-Output "▶️ Running script: $scriptPath"
          & $scriptPath
          Write-Output "✅ Script executed successfully: $scriptPath"
        } else {
          Write-Output "❌ Script not found: $scriptPath"
        }
      register: run_script_result
      ignore_errors: yes
      changed_when: "'executed successfully' in run_script_result.stdout"

    - name: Show script execution output
      ansible.builtin.debug:
        var: run_script_result.stdout

  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
