---
- hosts: all
  gather_facts: yes
  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"

  tasks:
    - name: Rename existing DymocksLoyalty folder if it exists
      win_shell: |
        if (Test-Path "C:\ARFiles\DymocksLoyaltyUpgrade") {
          Rename-Item -Path "C:\ARFiles\DymocksLoyaltyUpgrade" -NewName "C:\ARFiles\DymocksLoyaltyUpgrade_V2.8009.0.10" -Force
        }

    - name: Copy DymocksLoyalty folder from remote machine to local machine
      win_shell: |
        robocopy "\\10.100.10.200\ARFiles\DymocksLoyaltyUpgrade" "C:\ARFiles\DymocksLoyaltyUpgrade" /E /NFL /NDL /NP /R:3 /W:5
      register: robocopy_result
      failed_when: "robocopy_result.rc > 7"

    - name: Show robocopy output
      ansible.builtin.debug:
        var: robocopy_result.stdout_lines

  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
