- hosts: all
  gather_facts: yes
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only

  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"

  tasks:
    - name: Run inline version report
      ansible.windows.win_powershell:
        script: |
          $hostname = $env:COMPUTERNAME
          $os = (Get-CimInstance Win32_OperatingSystem).Caption
          [PSCustomObject]@{ Hostname = $hostname; OS = $os }
      register: host_result

    - name: Save host result as fact
      set_fact:
        host_report: "{{ host_result.output }}"

    - name: Generate report on the host
      template:
        src: report.j2
        dest: C:\ARFILES\windows_report.txt
      vars:
        all_hosts_data: "{{ host_report }}"
