---
- hosts: all
  tasks:
  - name: Run local script
    win_shell: 'C:\ARFiles\UpgradeMay2024\killprocess.ps1'
  - name: Display target IP
    debug:
      msg: "Pinging target: {{ survey_ip }}"
  gather_facts: yes
  become: True
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"
