---
- hosts: all
  tasks:
  #- name: Run local script 
    #win_shell: 'C:\ARFiles\UpgradeMay2024\killprocess.ps1'
  - name: copy  files
    copy:
      src: \\10.100.{{ survey_ip }}.207\ARFiles\UpgradeMay2024\upgradeApplicationSOR.ps1
      dest: C:\ARFiles\UpgradeMay2024\upgradeApplicationSOR.ps1
      remote_src: yes
  gather_facts: yes
  become: True
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"
