---
- hosts: all
  gather_facts: yes  # Placed at the correct level

  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"

  tasks:
    - name: Run local script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\ARFiles\UpgradeMay2024\killprocess.ps1"

    - name: Rename existing DymocksBooklover folder if it exists
      win_shell: |
        if (Test-Path "C:\Program Files (x86)\AdvanceRetail\EXE\Plugins\DymocksBooklover") {
          Rename-Item -Path "C:\Program Files (x86)\AdvanceRetail\EXE\Plugins\DymocksBooklover" -NewName "DymocksBooklover_old" -Force
        }
        
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
