---
- name: win_ping
  hosts: all
# hosts: "{{ variable_host }}"
  become: false
  gather_facts: false
  tasks:
     - name: test ping
       ansible.windows.win_ping:
       #delegate_to: "{{ variable_host }}"
       #delegate_facts: true
