---
- hosts: all
  tasks:
  - name: Run local script 
    win_shell: 'C:\ARFiles\UpgradeMay2024\killprocess.ps1'
  - name: Copy DymocksBooklover folder from remote machine to local machine
    win_shell: robocopy "\\10.100.{{ survey_ip }}.207\AdvanceRetail\EXE\Plugins\DymocksBooklover" "C:\Program Files (x86)\AdvanceRetail\EXE\Plugins\DymocksBooklover" /E /NFL /NDL /NP /R:3 /W:5
    register: robocopy_result
    ignore_errors: yes
  - name: Show robocopy output
    debug:
      var: robocopy_result.stdout_lines
  gather_facts: yes
  become: True
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_pass: "{{ password }}"
