---
- name: win_ping
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: Display target IP
      debug:
        msg: "Pinging target: {{ target_host }}"

    - name: Test ping
      ansible.windows.win_ping:
      delegate_to: "{{ target_host }}"
