---
- name: Run PowerShell script, rename folder, and copy files
  hosts: all
  gather_facts: false

  vars:
    target_ip: "{{ survey_ip }}"  
    remote_ip: "10.100.{{ target_ip }}.207"
    remote_path: "\\\\{{ remote_ip }}\\AdvanceRetail\\EXE\\Plugins\\DymocksBooklover"
    local_plugins_path: "C:\\Program Files (x86)\\AdvanceRetail\\EXE\\Plugins"
    local_script_path: "C:\\ARFiles\\UpgradeMay2024\\killprocess.ps1"

  tasks:
    - name: Run killprocess PowerShell script
      ansible.windows.win_powershell:
        script: "{{ local_script_path }}"

    - name: Rename existing DymocksBooklover folder if it exists
      ansible.windows.win_powershell:
        script: |
          if (Test-Path "{{ local_plugins_path }}\\DymocksBooklover") {
            Rename-Item -Path "{{ local_plugins_path }}\\DymocksBooklover" -NewName "DymocksBooklover_old" -Force
          }

    - name: Copy DymocksBooklover folder from remote machine to local machine
      ansible.windows.win_shell: |
        robocopy "{{ remote_path }}" "{{ local_plugins_path }}\\DymocksBooklover" /E /NFL /NDL /NP /R:3 /W:5
    become: True
    become_method: runas
    become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    vars:
      ansible_become_user: "{{ username }}"
      ansible_become_pass: "{{ password }}"
