---
- name: Run test.bat and display output.txt
  hosts: all
  gather_facts: no

  tasks:
    - name: Run test.bat
      win_command: cmd.exe /c "C:\test\test.bat"
      register: bat_output
      ignore_errors: yes

    - name: Show .bat execution stdout
      ansible.builtin.debug:
        var: bat_output.stdout_lines

    - name: Read output.txt using type command
      win_command: type C:\test\output.txt
      register: output_file

    - name: Display output.txt contents
      debug:
        msg: "{{ output_file.stdout }}"

