---
- name: Run test.bat and check output files
  hosts: all
  gather_facts: no

  tasks:
    - name: Run test.bat
      win_command: cmd.exe /c "C:\test\test.bat"
      register: bat_output
      ignore_errors: yes

    - name: Show test.bat stdout
      debug:
        var: bat_output.stdout_lines

    - name: List files in C:\test
      win_command: dir C:\test
      register: dir_output

    - name: Show directory listing of C:\test
      debug:
        msg: "{{ dir_output.stdout }}"

    - name: Read output.txt if exists
      win_stat:
        path: C:\test\output.txt
      register: output_stat

    - name: Read output.txt content
      win_command: type C:\test\output.txt
      register: output_file
      when: output_stat.stat.exists

    - name: Show output.txt contents
      debug:
        msg: "{{ output_file.stdout }}"
      when: output_stat.stat.exists


