---
- name: Run test.bat from C:\test
  hosts: all
  gather_facts: no

  tasks:
    - name: Run test.bat
      win_command: cmd.exe /c "C:\test\test2.bat"
      register: bat_output
      ignore_errors: yes

    - name: Show .bat output
      ansible.builtin.debug:
        var: bat_output.stdout_lines

    - name: Read the generated output file
      win_slurp:
        src: C:\test\output.txt
      register: output_file

    - name: Display output
      debug:
        msg: "{{ output_file.content | b64decode }}"
