---
- name: Run test.bat and wait for output.txt in C:\test
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure C:\test directory exists
      win_file:
        path: C:\test
        state: directory

    - name: Run test.bat
      win_command: cmd.exe /c "C:\test\test.bat"
      register: bat_output
      ignore_errors: yes

    - name: Show test.bat stdout
      debug:
        var: bat_output.stdout_lines

