---
- name: Run test.bat and wait for output.txt in C:\test
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure C:\test directory exists
      win_file:
        path: C:\test
        state: directory

    - name: Run test.bat
      win_command: cmd.exe /c "C:\test\test.bat"
      register: bat_output
      ignore_errors: yes

    - name: Show test.bat stdout
      debug:
        var: bat_output.stdout_lines

    - name: Wait for output.txt to be created (max 30s)
      win_wait_for:
        path: C:\test\output.txt
        state: present
        timeout: 30

    - name: Check if output.txt exists
      win_stat:
        path: C:\test\output.txt
      register: output_stat

    - name: Read output.txt content if it exists
      win_command: type C:\test\output.txt
      register: output_file
      when: output_stat.stat.exists
      ignore_errors: yes

    - name: Show output.txt contents if file found
      debug:
        msg: "{{ output_file.stdout }}"
      when: output_stat.stat.exists

    - name: Warn if output.txt not found
      debug:
        msg: "output.txt does not exist yet."
      when: not output_stat.stat.exists
