---
- name: Run test.bat and wait for output.txt in C:\test
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure C:\test directory exists
      win_file:
        path: C:\test
        state: directory

    - name: Run test.bat
      win_command: cmd.exe /c "C:\test\test.bat"
      register: bat_output
      ignore_errors: yes

    - name: Show test.bat stdout
      debug:
        var: bat_output.stdout_lines

    - name: Wait for output.txt to be created (max 30s)
      win_wait_for:
        path: C:\test\output.txt
        state: present
        timeout: 30

    - name: Read output.txt content
      win_command: type C:\test\output.txt
      register: output_file
      ignore_errors: yes

    - name: Show output.txt contents
      debug:
        msg: "{{ output_file.stdout | default('output.txt not found') }}"
